image: golang:1.11

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - mkdir -p /go/src/gitlab.com/thomas.poignant /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/thomas.poignant/fizzbuzz
  - ln -s /go/src/gitlab.com/thomas.poignant /go/src/_/builds/thomas.poignant
  - cd /go/src/gitlab.com/thomas.poignant/fizzbuzz
  - chmod +x scripts/*.sh
  - make deps

unit_tests:
  stage: test
  script:
    - make test

lint_code:
  stage: test
  script:
    - make lint

coverage:
  stage: test
  script:
    - make coverage

build:
  stage: build
  script:
    - make
